-- OT-17: Tabla append-only de snapshots de conteo + índices de consultas supervisor
-- Ejecutar después de 002_empleados_schema.sql

BEGIN;

CREATE TABLE IF NOT EXISTS public.corte_conteo_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  corte_id uuid NOT NULL REFERENCES public.cortes(id) ON DELETE CASCADE,
  attempt_number integer NOT NULL CHECK (attempt_number > 0),
  fase_actual integer NOT NULL CHECK (fase_actual BETWEEN 0 AND 3),
  penny numeric(12,2) NOT NULL DEFAULT 0,
  nickel numeric(12,2) NOT NULL DEFAULT 0,
  dime numeric(12,2) NOT NULL DEFAULT 0,
  quarter numeric(12,2) NOT NULL DEFAULT 0,
  dollar_coin numeric(12,2) NOT NULL DEFAULT 0,
  bill1 numeric(12,2) NOT NULL DEFAULT 0,
  bill5 numeric(12,2) NOT NULL DEFAULT 0,
  bill10 numeric(12,2) NOT NULL DEFAULT 0,
  bill20 numeric(12,2) NOT NULL DEFAULT 0,
  bill50 numeric(12,2) NOT NULL DEFAULT 0,
  bill100 numeric(12,2) NOT NULL DEFAULT 0,
  credomatic numeric(12,2) NOT NULL DEFAULT 0,
  promerica numeric(12,2) NOT NULL DEFAULT 0,
  bank_transfer numeric(12,2) NOT NULL DEFAULT 0,
  paypal numeric(12,2) NOT NULL DEFAULT 0,
  gastos_dia jsonb NOT NULL DEFAULT '[]'::jsonb,
  source text NOT NULL CHECK (source IN ('autosave','manual','fase_change','test_append_only')),
  captured_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_corte_conteo_snapshots_lookup
  ON public.corte_conteo_snapshots (corte_id, attempt_number, captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_cortes_estado_finalizado
  ON public.cortes (estado, finalizado_at DESC);

ALTER TABLE public.corte_conteo_snapshots ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS anon_rw_corte_conteo_snapshots ON public.corte_conteo_snapshots;
CREATE POLICY anon_rw_corte_conteo_snapshots
  ON public.corte_conteo_snapshots
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

COMMIT;

NOTIFY pgrst, 'reload schema';
